name: Building Conda

on: [workflow_dispatch]

jobs:

  conda-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        python-version: ['3.7', '3.8', '3.9', '3.10']
        torch-version: [1.9.0, 1.10.0, 1.11.0]
        cuda-version: ['cpu', 'cu102', 'cu113', 'cu115']
        exclude:
          - os: windows-latest
            cuda-version: 'cu101'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda for Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Free up disk space
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo rm -rf /usr/share/dotnet

      - name: Install Conda packages
        run: |
          conda install conda-build conda-verify --yes
        shell:
          bash -l {0}

      - name: Install CUDA ${{ matrix.cuda-version }}
        if: ${{ matrix.cuda-version != 'cpu' }}
        run: |
          bash .github/workflows/cuda/${{ matrix.cuda-version }}-${{ runner.os }}.sh
        shell:
          bash

      - name: Build Conda package
        run: |
          ./conda/torch-points-kernels/build_conda.sh ${{ matrix.python-version }} ${{ matrix.torch-version }} ${{ matrix.cuda-version }}
        shell:
          bash -l {0}

      - name: Publish Conda package
        run: |
          conda install anaconda-client --yes
          anaconda upload --force --user eal --label main $HOME/conda-bld/*/*.tar.bz2
        env:
          ANACONDA_API_TOKEN: ${{ secrets.EAL_CONDA_TOKEN }}
        shell:
          bash -l {0}
